# ===============================================
# Perfil de Desarrollo Local (dev)
# Activar con: --spring.profiles.active=dev o SPRING_PROFILES_ACTIVE=dev
# ===============================================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

