spring.application.name=grand-prix-tracker

# ===============================================
# Configuración de Base de Datos (Supabase PostgreSQL)
# Reemplaza los valores con las credenciales de tu proyecto en Supabase:
# (Dashboard de Supabase -> Project Settings -> Database -> Connection string)
# ===============================================
# Conexión Session Pooler IPv4:
spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.zprznayvpeijjoiknird
spring.datasource.password=uade123uade
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================================
# Configuración de JPA / Hibernate
# ===============================================
# 'none' para respetar y no alterar el esquema existente en Supabase
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
